#!/bin/sh
[ -d /oaaa ] || { echo "/oaaa not found"; exit 1; }
[ "$(id -u)" -eq 0 ] || { echo "must be run as root"; exit 1; }
cat <<EOF > /oaaa/oaaa-command-stage1
#!/bin/sh
/bin/oaaat
rm /data/oaaa-command-stage1
/bin/reisub
exit
EOF
reboot
