#!/bin/bash
if [[ $EUID -ne 0 ]]; then echo "This script must be run as root.";exit 1;fi
rm -rf iso
cp -r /usr/share/archiso/configs/releng/ iso
cd iso
cp ../oaaa-install airootfs/usr/local/bin/
cp ../*.erofs airootfs/etc/system.erofs
cat >profiledef.sh<<'EOF'
#!/usr/bin/env bash
# shellcheck disable=SC2034

iso_name="oaaa"
iso_label="OAAARCH_$(date --date="@${SOURCE_DATE_EPOCH:-$(date +%s)}" +%Y%m)"
iso_publisher="TheOddCell <https://oddcell.ca/>"
iso_application="Odd And Atomic Arch Live/Rescue Disk"
iso_version="$(date --date="@${SOURCE_DATE_EPOCH:-$(date +%s)}" +%Y.%m.%d)"
install_dir="oaaa"
buildmodes=('iso')
bootmodes=('bios.syslinux'
           'uefi.systemd-boot')
pacman_conf="pacman.conf"
airootfs_image_type="squashfs"
airootfs_image_tool_options=('-comp' 'xz' '-Xbcj' 'x86' '-b' '1M' '-Xdict-size' '1M')
bootstrap_tarball_compression=('zstd' '-c' '-T0' '--auto-threads=logical' '--long' '-19')
file_permissions=(
  ["/etc/shadow"]="0:0:400"
  ["/root"]="0:0:750"
  ["/root/.automated_script.sh"]="0:0:755"
  ["/root/.gnupg"]="0:0:700"
  ["/usr/local/bin/choose-mirror"]="0:0:755"
  ["/usr/local/bin/Installation_guide"]="0:0:755"
  ["/usr/local/bin/livecd-sound"]="0:0:755"
  ["/usr/local/bin/oaaa-install"]="0:0:755"
)
EOF
echo "Welcome to oaaa! Use oaaa-install with /etc/system.erofs to install. PLEASE NOTE: any storage except for SATA SSDs may not work and are unsupported untill the driver situation is fixed.">>airootfs/etc/issue
cd ..
mkarchiso -v -r -w "$(mktemp -u)" -o . iso
rm -rf iso
