#!/bin/sh
if [ "$0" != "/oaaa/oaaat" ] && [ -f "/oaaa/oaaat" ]; then # yes hardcoded to oaaa, in the initramfs it will be using the same oaaat.
  echo "Using system oaaat."
  exec "/oaaa/oaaat"
fi
reisub() {
  if [ "$state" = "loaded-system" ]; then
    reboot
  else
    printf '%s\n' 1 > /proc/sys/kernel/sysrq || return 1
    printf '%s\n' r e i s u b | while IFS= read -r key; do
      printf '%s' "$key" > /proc/sysrq-trigger || exit 1
      sleep 2
    done
  fi
}
choose() {
  gum choose --header.foreground="" --selected.foreground="" --cursor.foreground="" --no-show-help --header=""|tee /dev/stderr
}
if [ -z "$alreadyoat" ]; then
  export alreadyoat="yes"
  gum join "$(gum style --border=double --padding="0 1" oaaat)" "$(gum style --border=double --padding="0 1" the oaaa tool)"
  gum style --border=double --padding="0 1" "What would you like to do?"
fi
state=""
datadir=""
choices=""
choices="${choices}Factory Reset\nCleanup Reset\n"
if [ -d "/data" ]; then
  datadir="/data"
  if ! { set -- "$datadir"/images/* && [ "$#" -eq 1 ] && [ -e "$1" ]; }; then
    choices="${choices}Rollback\n"
  fi
  if grep -q "oaaa.stage=2" /proc/cmdline 2>/dev/null; then
    state="stage2"
  else
    state="stage1"
    if ! { set -- "$datadir"/images/* && [ "$#" -eq 1 ] && [ -e "$1" ]; }; then
      choices="${choices}Delete Snapshot\n"
    fi
  fi
elif [ -d "/oaaa" ]; then
  state="loaded-system"
  datadir="/oaaa"
  if [ "$(ls "$datadir/images" | wc -l)" -ne 1 ]; then
    choices="${choices}Rollback\nDelete Snapshot\n"
  fi
  choices="${choices}Download System Update\nUpdate OAAA\nReboot To OAAAT\n"
else
  echo "ERROR: not on oaaa"
  exit 1
fi
choices="${choices}Reboot\n"
if [ "$(id -u)" != 0 ]; then
  echo "ERROR: not root"
  exit 1
fi
if [ -z "$choices" ]; then
  echo "ERROR: nothing to do"
  exit 1
fi
choices="${choices}Exit\n"
choice="$(printf "$choices"|choose)"
if [ "$choice" = "Rollback" ]; then
  choice2="$(ls -t "$datadir/images"|choose)"
  if [ -n "$choice2" ] && [ "$choice2" != "nothing selected" ]; then
    touch "$datadir/images/$choice2"
    echo "Rollback Ready!"
  fi
elif [ "$choice" = "Delete Snapshot" ]; then
  if [ "$state" = "loaded-system" ]; then
    current="$(basename "$(cat /sys/block/loop0/loop/backing_file 2>/dev/null)")"
    choice2="$(ls -t "$datadir/images" | grep -vx "$current" | choose)"
  else
    choice2="$(ls -t "$datadir/images"|choose)"
  fi
  if [ -n "$choice2" ] && [ "$choice2" != "nothing selected" ]; then
    rm "$datadir/images/$choice2"
    echo "Snapshot Deleted!"
  fi
elif [ "$choice" = "Factory Reset" ]; then
  echo "Are you sure? This will *DELETE ALL YOUR USER DATA* and is not recoverable."
  if [ "$(printf 'Cancel\nYes\n'|choose)" = "Yes" ]; then
    touch "$datadir/oaaa-factory-reset"
    reisub
    echo "Will do on restart."
  fi
elif [ "$choice" = "Cleanup Reset" ]; then
  echo "Are you sure? This will *DELETE EVERYTHING* (except for your user data) and is not recoverable."
  if [ "$(printf 'Cancel\nYes\n'|choose)" = "Yes" ]; then
    touch "$datadir/oaaa-cleanup"
    echo "Will do on restart."
  fi
elif [ "$choice" = "Download System Update" ]; then
  base="system-$(date +%Y-%m-%d)"
  f="$datadir/images/$base.erofs"
  i=1
  while [ -e "$f" ]; do
    i=$((i + 1))
    f="$datadir/images/$base-$i.erofs"
  done
  curl -fL -o "$f" https://files.obsidianos.xyz/~odd/oaaa/system.erofs
  echo "Updated!"
elif [ "$choice" = "Update OAAA" ]; then
  curl -fL -o "/boot/initramfs-oaaa.img" https://files.obsidianos.xyz/~odd/oaaa/initramfs-oaaa.img
  cp /boot/initramfs-oaaa.img "$datadir"
  curl -fL -o "/boot/vmlinuz-linux" https://files.obsidianos.xyz/~odd/oaaa/vmlinuz-oaaa
  echo "Updated!"
elif [ "$choice" = "Reboot" ]; then
  reisub
else
  echo "Done."
  exit 0
fi
exec $0
